# Generated by Django 2.0.2 on 2018-03-05 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0010_auto_20180220_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_errors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
